### ISSUE TITLE
Bondtech LGX lite // Canbus // ball bearing filament sensor

### ISSUE THREAD

**Issue by ricosander** [sorted01/Filametrix#10]
I like the idea of cutting the filament, b/c I already ran into problems with the sensor and the tip finding its way there.
If not planned already, could you add support for the bondtech lgx lite?
Maybe the ball bearing filament sensor could be optional, with the cutting feature it should not be a problem anyway.

I guess the lgx lite is widely used along with the Canbus 2209.

**Comment by sorted01** [comment]
https://www.printables.com/de/model/576122-lgx-lite-stealthburner-filament-cutter
