### ISSUE TITLE
Happy Hare Update

### ISSUE THREAD

**Issue by drecoor** [sorted01/Filametrix#14]
Happy Hare seems to have updated I think, and the provided gcodes aren't working anymore. It looks like ercf_software.cfg was replaced with mmu_software.cfg, and there is no variable_standalone option anymore. The ercf_additional.cfg file is not working with the update as well.

**Comment by sorted01** [comment]
Thank you for the hint. Was expecting that. Unfortunately I currently have no time to take a look on how to fix it. This will take a few weeks. (2-3). Sorry for that. If someone can check it earlier I will update the GitHub
