### ISSUE TITLE
Which CW2 motor plate to use?

### ISSUE THREAD

**Issue by JAMMnGA** [sorted01/Filametrix#15]
I printed your EBB main body and the current CW2 motor plate at VoronDesign.  The  top alignment tab on the main body does not match the recess on the motor plate.  Which motor plate should I use?

**Comment by sorted01** [comment]
I got pinged in discord regarding that topic. Can you share a screenshot? I will try to update

**Comment by sorted01** [comment]
Stealthburner has seen a small update from Voron team. Due to that the motor plate doesn't fit anymore. I've uploaded the motor plate you need for filametrix. These parts will flush together again.
