### ISSUE TITLE
Is it v6 compatible?

### ISSUE THREAD

**Issue by FrAn3030** [sorted01/Filametrix#6]
Hi i would like to us your mód with normal v6

**Comment by FrAn3030** [comment]
is there any chance too make a v6 mount or is it compatible with revo?

**Comment by Heiliger-Gral** [comment]
> is there any chance too make a v6 mount or is it compatible with revo?

you mean for Groove-Mount .. I'm looking for something like that right now :)

**Comment by sorted01** [comment]
As the hotend is to high for this design I don't think so. You can check the "motivation" text. There I've linked a design which uses the V6 hotend
